export const SUPABASE_URL = "https://yssmueithjdfvhhoraex.supabase.co";
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlzc211ZWl0aGpkZnZoaG9yYWV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjk5NDg2MjgsImV4cCI6MjA0NTUyNDYyOH0.QwlwZJfBSJh0YQhuFpAHSKevHajg-2zNVAqTElLaEa8";
